AllCops:   
  Exclude:     
    - 'db/schema.rb'
    - 'bin/*'
    #- 'config/**/*'     
    #- 'script/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 80

Metrics/LineLength:
  Max: 999

Bundler/OrderedGems:
  Enabled: false